#!/bin/sh

. ./common.sh

echo "GOING to " ${DATATYPE}

rm -rf ../data/${DATATYPE}
rm -rf ../sql/${DATATYPE}

mkdir -p ../data/${DATATYPE}
mkdir -p ../sql/${DATATYPE}

./extract-csv.sh
mv *.csv ../data/${DATATYPE}
./create-sql.sh
mv *.sql ../sql/${DATATYPE}
mv *column_labels ../data/${DATATYPE}

