#!/bin/bash

dropdb --if-exists SLIPRATE_db 
createdb SLIPRATE_db

psql postgresql://postgres:example@localhost/SLIPRATE_db << AAA

  CREATE EXTENSION postgis;
  SELECT PostGIS_Version();

  \i '/home/postgres/EGD/sql/sliprate1/setup_schema.sql';
  \i '/home/postgres/EGD/sql/sliprate1/setup_sliprate_tb.sql';
  \i '/home/postgres/EGD/sql/sliprate1/linkup_traces.sql';

  DROP ROLE webonly;
  CREATE ROLE webonly WITH LOGIN PASSWORD 'scec';
  GRANT SELECT ON ALL TABLES IN SCHEMA public TO webonly;
  REVOKE CREATE ON SCHEMA public FROM PUBLIC;

  \dp
  \q

AAA

