CREATE TABLE SLIPRATE_tb (
   gid             serial PRIMARY KEY,
   NSHM23RateId    VARCHAR(10) NOT NULL,
   SCECId          VARCHAR(10) UNIQUE NOT NULL,
   LastUpdate      VARCHAR(12) NOT NULL,
   Longitude       float DEFAULT 0.0,  
   Latitude        float DEFAULT 0.0,  
   FaultName       VARCHAR(200) NOT NULL,
   NSHM23FaultId   VARCHAR(20) NOT NULL,
   State           VARCHAR(10) NOT NULL,
   SiteName        VARCHAR(100) NOT NULL,
   DistToCFMFault  float DEFAULT 0.0,
   CFM7ObjectName  VARCHAR(100) NOT NULL,
   Observation     VARCHAR(2000),
   PrefRate        VARCHAR(50),
   LowRate         float default 0.0,
   HighRate        float default 0.0,
   RateUnct        VARCHAR(400) NOT NULL,
   RateType        VARCHAR(400) NOT NULL,
   ReptReint       VARCHAR(400), 
   OffsetType      VARCHAR(400) NOT NULL,
   AgeType         VARCHAR(400) NOT NULL,
   NumEvents       VARCHAR(400) NOT NULL,
   RateAge         VARCHAR(100) NOT NULL,
   QbinMin         float default 0.0,
   QbinMax         float default 0.0,
   UCERF3AppB      VARCHAR(400) NOT NULL,
   ShortReference  VARCHAR(1000) NOT NULL,
   Links           VARCHAR(1000) NOT NULL,
   FullReference   VARCHAR(5000) NOT NULL
);

SELECT AddGeometryColumn('','sliprate_tb','geom','0','POINT',2);
